name: udacity_dvc
channels:
  - anaconda
  - defaults
dependencies:
  - pip
  - python=3.8
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - pytest
      - requests
      - fastapi==0.63.0
      - uvicorn
      - gunicorn